trigger:
  - none

pr: none

pool:
  vmImage: ubuntu-latest

schedules:
  - cron: "0 1 * * *"
    displayName: Daily midnight +1 build
    branches:
      include:
        - master
    always: true

jobs:
  - job: Test
    timeoutInMinutes: 40
    steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'DevKeyVaultReader'
          KeyVaultName: 'webdev-dsm'
          SecretsFilter: '*'
          RunAsPreJob: false
      - task: NodeTool@0
        inputs:
          versionSpec: '14.13.1'
      - script: npm ci
      - task: Bash@3
        displayName: Set Browserstack credentials and run Tests
        inputs:
          targetType: 'inline'
          script: |
            export browserstackuser=gskidazure_QcPKzv7HaK
            export browserstackkey=$(GSKWebDevDsmBrowserStackAccKey)
            #export PERCY_TOKEN=$(Percy-Webdev-dsm)
            npm run ci -- --build-name=$(Build.DefinitionName).$(Build.BuildNumber) --env configFile=staging,device=desktop,TAGS='@staging and @desktop'
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'build_artifacts/**/*.xml'


npx cypress run -- browser chrome,firefox --parallel 